/** @see https://en.wikipedia.org/wiki/ISO_3166-1 */
var CountryCodeData = [
    { Name:"Afghanistan", Code2:"AF", Code3:"AFG", NumCode:"004", ISO:"ISO 3166-2:AF", Independent: "Yes" },
    { Name:"Islands Åland Islands", Code2:"AX", Code3:"ALA", NumCode:"248", ISO:"ISO 3166-2:AX", Independent: "No" },
    { Name:"Albania", Code2:"AL", Code3:"ALB", NumCode:"008", ISO:"ISO 3166-2:AL", Independent: "Yes" },
    { Name:"Algeria", Code2:"DZ", Code3:"DZA", NumCode:"012", ISO:"ISO 3166-2:DZ", Independent: "Yes" },
    { Name:"American Samoa", Code2:"AS", Code3:"ASM", NumCode:"016", ISO:"ISO 3166-2:AS", Independent: "No" },
    { Name:"Andorra", Code2:"AD", Code3:"AND", NumCode:"020", ISO:"ISO 3166-2:AD", Independent: "Yes" },
    { Name:"Angola", Code2:"AO", Code3:"AGO", NumCode:"024", ISO:"ISO 3166-2:AO", Independent: "Yes" },
    { Name:"Anguilla", Code2:"AI", Code3:"AIA", NumCode:"660", ISO:"ISO 3166-2:AI", Independent: "No" },
    { Name:"Antarctica", Code2:"AQ", Code3:"ATA", NumCode:"010", ISO:"ISO 3166-2:AQ", Independent: "No" },
    { Name:"Antigua and Barbuda", Code2:"AG", Code3:"ATG", NumCode:"028", ISO:"ISO 3166-2:AG", Independent: "Yes" },
    { Name:"Argentina", Code2:"AR", Code3:"ARG", NumCode:"032", ISO:"ISO 3166-2:AR", Independent: "Yes" },
    { Name:"Armenia", Code2:"AM", Code3:"ARM", NumCode:"051", ISO:"ISO 3166-2:AM", Independent: "Yes" },
    { Name:"Aruba", Code2:"AW", Code3:"ABW", NumCode:"533", ISO:"ISO 3166-2:AW", Independent: "No" },
    { Name:"Australia", Code2:"AU", Code3:"AUS", NumCode:"036", ISO:"ISO 3166-2:AU", Independent: "Yes" },
    { Name:"Austria", Code2:"AT", Code3:"AUT", NumCode:"040", ISO:"ISO 3166-2:AT", Independent: "Yes" },
    { Name:"Azerbaijan", Code2:"AZ", Code3:"AZE", NumCode:"031", ISO:"ISO 3166-2:AZ", Independent: "Yes" },
    { Name:"Bahamas", Code2:"BS", Code3:"BHS", NumCode:"044", ISO:"ISO 3166-2:BS", Independent: "Yes" },
    { Name:"Bahrain", Code2:"BH", Code3:"BHR", NumCode:"048", ISO:"ISO 3166-2:BH", Independent: "Yes" },
    { Name:"Bangladesh", Code2:"BD", Code3:"BGD", NumCode:"050", ISO:"ISO 3166-2:BD", Independent: "Yes" },
    { Name:"Barbados", Code2:"BB", Code3:"BRB", NumCode:"052", ISO:"ISO 3166-2:BB", Independent: "Yes" },
    { Name:"Belarus", Code2:"BY", Code3:"BLR", NumCode:"112", ISO:"ISO 3166-2:BY", Independent: "Yes" },
    { Name:"Belgium", Code2:"BE", Code3:"BEL", NumCode:"056", ISO:"ISO 3166-2:BE", Independent: "Yes" },
    { Name:"Belize", Code2:"BZ", Code3:"BLZ", NumCode:"084", ISO:"ISO 3166-2:BZ", Independent: "Yes" },
    { Name:"Benin", Code2:"BJ", Code3:"BEN", NumCode:"204", ISO:"ISO 3166-2:BJ", Independent: "Yes" },
    { Name:"Bermuda", Code2:"BM", Code3:"BMU", NumCode:"060", ISO:"ISO 3166-2:BM", Independent: "No" },
    { Name:"Bhutan", Code2:"BT", Code3:"BTN", NumCode:"064", ISO:"ISO 3166-2:BT", Independent: "Yes" },
    { Name:"Bolivia (Plurinational State of)", Code2:"BO", Code3:"BOL", NumCode:"068", ISO:"ISO 3166-2:BO", Independent: "Yes" },
    { Name:"Bonaire, Sint Eustatius and Saba", Code2:"BQ", Code3:"BES", NumCode:"535", ISO:"ISO 3166-2:BQ", Independent: "No" },
    { Name:"Bosnia and Herzegovina", Code2:"BA", Code3:"BIH", NumCode:"070", ISO:"ISO 3166-2:BA", Independent: "Yes" },
    { Name:"Botswana", Code2:"BW", Code3:"BWA", NumCode:"072", ISO:"ISO 3166-2:BW", Independent: "Yes" },
    { Name:"Bouvet Island", Code2:"BV", Code3:"BVT", NumCode:"074", ISO:"ISO 3166-2:BV", Independent: "No" },
    { Name:"Brazil", Code2:"BR", Code3:"BRA", NumCode:"076", ISO:"ISO 3166-2:BR", Independent: "Yes" },
    { Name:"British Indian Ocean Territory", Code2:"IO", Code3:"IOT", NumCode:"086", ISO:"ISO 3166-2:IO", Independent: "No" },
    { Name:"Brunei Darussalam", Code2:"BN", Code3:"BRN", NumCode:"096", ISO:"ISO 3166-2:BN", Independent: "Yes" },
    { Name:"Bulgaria", Code2:"BG", Code3:"BGR", NumCode:"100", ISO:"ISO 3166-2:BG", Independent: "Yes" },
    { Name:"Burkina Faso", Code2:"BF", Code3:"BFA", NumCode:"854", ISO:"ISO 3166-2:BF", Independent: "Yes" },
    { Name:"Burundi", Code2:"BI", Code3:"BDI", NumCode:"108", ISO:"ISO 3166-2:BI", Independent: "Yes" },
    { Name:"Cabo Verde", Code2:"CV", Code3:"CPV", NumCode:"132", ISO:"ISO 3166-2:CV", Independent: "Yes" },
    { Name:"Cambodia", Code2:"KH", Code3:"KHM", NumCode:"116", ISO:"ISO 3166-2:KH", Independent: "Yes" },
    { Name:"Cameroon", Code2:"CM", Code3:"CMR", NumCode:"120", ISO:"ISO 3166-2:CM", Independent: "Yes" },
    { Name:"Canada", Code2:"CA", Code3:"CAN", NumCode:"124", ISO:"ISO 3166-2:CA", Independent: "Yes" },
    { Name:"Cayman Islands", Code2:"KY", Code3:"CYM", NumCode:"136", ISO:"ISO 3166-2:KY", Independent: "No" },
    { Name:"Central African Republic", Code2:"CF", Code3:"CAF", NumCode:"140", ISO:"ISO 3166-2:CF", Independent: "Yes" },
    { Name:"Chad", Code2:"TD", Code3:"TCD", NumCode:"148", ISO:"ISO 3166-2:TD", Independent: "Yes" },
    { Name:"Chile", Code2:"CL", Code3:"CHL", NumCode:"152", ISO:"ISO 3166-2:CL", Independent: "Yes" },
    { Name:"China", Code2:"CN", Code3:"CHN", NumCode:"156", ISO:"ISO 3166-2:CN", Independent: "Yes" },
    { Name:"Christmas Island", Code2:"CX", Code3:"CXR", NumCode:"162", ISO:"ISO 3166-2:CX", Independent: "No" },
    { Name:"Cocos (Keeling) Islands", Code2:"CC", Code3:"CCK", NumCode:"166", ISO:"ISO 3166-2:CC", Independent: "No" },
    { Name:"Colombia", Code2:"CO", Code3:"COL", NumCode:"170", ISO:"ISO 3166-2:CO", Independent: "Yes" },
    { Name:"Comoros", Code2:"KM", Code3:"COM", NumCode:"174", ISO:"ISO 3166-2:KM", Independent: "Yes" },
    { Name:"Congo", Code2:"CG", Code3:"COG", NumCode:"178", ISO:"ISO 3166-2:CG", Independent: "Yes" },
    { Name:"Congo, Democratic Republic of the", Code2:"CD", Code3:"COD", NumCode:"180", ISO:"ISO 3166-2:CD", Independent: "Yes" },
    { Name:"Cook Islands", Code2:"CK", Code3:"COK", NumCode:"184", ISO:"ISO 3166-2:CK", Independent: "No" },
    { Name:"Costa Rica", Code2:"CR", Code3:"CRI", NumCode:"188", ISO:"ISO 3166-2:CR", Independent: "Yes" },
    { Name:"Côte d'Ivoire", Code2:"CI", Code3:"CIV", NumCode:"384", ISO:"ISO 3166-2:CI", Independent: "Yes" },
    { Name:"Croatia", Code2:"HR", Code3:"HRV", NumCode:"191", ISO:"ISO 3166-2:HR", Independent: "Yes" },
    { Name:"Cuba", Code2:"CU", Code3:"CUB", NumCode:"192", ISO:"ISO 3166-2:CU", Independent: "Yes" },
    { Name:"Curaçao", Code2:"CW", Code3:"CUW", NumCode:"531", ISO:"ISO 3166-2:CW", Independent: "No" },
    { Name:"Cyprus", Code2:"CY", Code3:"CYP", NumCode:"196", ISO:"ISO 3166-2:CY", Independent: "Yes" },
    { Name:"Czechia", Code2:"CZ", Code3:"CZE", NumCode:"203", ISO:"ISO 3166-2:CZ", Independent: "Yes" },
    { Name:"Denmark", Code2:"DK", Code3:"DNK", NumCode:"208", ISO:"ISO 3166-2:DK", Independent: "Yes" },
    { Name:"Djibouti", Code2:"DJ", Code3:"DJI", NumCode:"262", ISO:"ISO 3166-2:DJ", Independent: "Yes" },
    { Name:"Dominica", Code2:"DM", Code3:"DMA", NumCode:"212", ISO:"ISO 3166-2:DM", Independent: "Yes" },
    { Name:"Dominican Republic", Code2:"DO", Code3:"DOM", NumCode:"214", ISO:"ISO 3166-2:DO", Independent: "Yes" },
    { Name:"Ecuador", Code2:"EC", Code3:"ECU", NumCode:"218", ISO:"ISO 3166-2:EC", Independent: "Yes" },
    { Name:"Egypt", Code2:"EG", Code3:"EGY", NumCode:"818", ISO:"ISO 3166-2:EG", Independent: "Yes" },
    { Name:"El Salvador", Code2:"SV", Code3:"SLV", NumCode:"222", ISO:"ISO 3166-2:SV", Independent: "Yes" },
    { Name:"Equatorial Guinea", Code2:"GQ", Code3:"GNQ", NumCode:"226", ISO:"ISO 3166-2:GQ", Independent: "Yes" },
    { Name:"Eritrea", Code2:"ER", Code3:"ERI", NumCode:"232", ISO:"ISO 3166-2:ER", Independent: "Yes" },
    { Name:"Estonia", Code2:"EE", Code3:"EST", NumCode:"233", ISO:"ISO 3166-2:EE", Independent: "Yes" },
    { Name:"Eswatini", Code2:"SZ", Code3:"SWZ", NumCode:"748", ISO:"ISO 3166-2:SZ", Independent: "Yes" },
    { Name:"Ethiopia", Code2:"ET", Code3:"ETH", NumCode:"231", ISO:"ISO 3166-2:ET", Independent: "Yes" },
    { Name:"Falkland Islands (Malvinas)", Code2:"FK", Code3:"FLK", NumCode:"238", ISO:"ISO 3166-2:FK", Independent: "No" },
    { Name:"Faroe Islands", Code2:"FO", Code3:"FRO", NumCode:"234", ISO:"ISO 3166-2:FO", Independent: "No" },
    { Name:"Fiji", Code2:"FJ", Code3:"FJI", NumCode:"242", ISO:"ISO 3166-2:FJ", Independent: "Yes" },
    { Name:"Finland", Code2:"FI", Code3:"FIN", NumCode:"246", ISO:"ISO 3166-2:FI", Independent: "Yes" },
    { Name:"France", Code2:"FR", Code3:"FRA", NumCode:"250", ISO:"ISO 3166-2:FR", Independent: "Yes" },
    { Name:"French Guiana", Code2:"GF", Code3:"GUF", NumCode:"254", ISO:"ISO 3166-2:GF", Independent: "No" },
    { Name:"French Polynesia", Code2:"PF", Code3:"PYF", NumCode:"258", ISO:"ISO 3166-2:PF", Independent: "No" },
    { Name:"French Southern Territories", Code2:"TF", Code3:"ATF", NumCode:"260", ISO:"ISO 3166-2:TF", Independent: "No" },
    { Name:"Gabon", Code2:"GA", Code3:"GAB", NumCode:"266", ISO:"ISO 3166-2:GA", Independent: "Yes" },
    { Name:"Gambia", Code2:"GM", Code3:"GMB", NumCode:"270", ISO:"ISO 3166-2:GM", Independent: "Yes" },
    { Name:"Georgia", Code2:"GE", Code3:"GEO", NumCode:"268", ISO:"ISO 3166-2:GE", Independent: "Yes" },
    { Name:"Germany", Code2:"DE", Code3:"DEU", NumCode:"276", ISO:"ISO 3166-2:DE", Independent: "Yes" },
    { Name:"Ghana", Code2:"GH", Code3:"GHA", NumCode:"288", ISO:"ISO 3166-2:GH", Independent: "Yes" },
    { Name:"Gibraltar", Code2:"GI", Code3:"GIB", NumCode:"292", ISO:"ISO 3166-2:GI", Independent: "No" },
    { Name:"Greece", Code2:"GR", Code3:"GRC", NumCode:"300", ISO:"ISO 3166-2:GR", Independent: "Yes" },
    { Name:"Greenland", Code2:"GL", Code3:"GRL", NumCode:"304", ISO:"ISO 3166-2:GL", Independent: "No" },
    { Name:"Grenada", Code2:"GD", Code3:"GRD", NumCode:"308", ISO:"ISO 3166-2:GD", Independent: "Yes" },
    { Name:"Guadeloupe", Code2:"GP", Code3:"GLP", NumCode:"312", ISO:"ISO 3166-2:GP", Independent: "No" },
    { Name:"Guam", Code2:"GU", Code3:"GUM", NumCode:"316", ISO:"ISO 3166-2:GU", Independent: "No" },
    { Name:"Guatemala", Code2:"GT", Code3:"GTM", NumCode:"320", ISO:"ISO 3166-2:GT", Independent: "Yes" },
    { Name:"Guernsey", Code2:"GG", Code3:"GGY", NumCode:"831", ISO:"ISO 3166-2:GG", Independent: "No" },
    { Name:"Guinea", Code2:"GN", Code3:"GIN", NumCode:"324", ISO:"ISO 3166-2:GN", Independent: "Yes" },
    { Name:"Guinea-Bissau", Code2:"GW", Code3:"GNB", NumCode:"624", ISO:"ISO 3166-2:GW", Independent: "Yes" },
    { Name:"Guyana", Code2:"GY", Code3:"GUY", NumCode:"328", ISO:"ISO 3166-2:GY", Independent: "Yes" },
    { Name:"Haiti", Code2:"HT", Code3:"HTI", NumCode:"332", ISO:"ISO 3166-2:HT", Independent: "Yes" },
    { Name:"Heard Island and McDonald Islands", Code2:"HM", Code3:"HMD", NumCode:"334", ISO:"ISO 3166-2:HM", Independent: "No" },
    { Name:"Holy See", Code2:"VA", Code3:"VAT", NumCode:"336", ISO:"ISO 3166-2:VA", Independent: "Yes" },
    { Name:"Honduras", Code2:"HN", Code3:"HND", NumCode:"340", ISO:"ISO 3166-2:HN", Independent: "Yes" },
    { Name:"Hong Kong", Code2:"HK", Code3:"HKG", NumCode:"344", ISO:"ISO 3166-2:HK", Independent: "No" },
    { Name:"Hungary", Code2:"HU", Code3:"HUN", NumCode:"348", ISO:"ISO 3166-2:HU", Independent: "Yes" },
    { Name:"Iceland", Code2:"IS", Code3:"ISL", NumCode:"352", ISO:"ISO 3166-2:IS", Independent: "Yes" },
    { Name:"India", Code2:"IN", Code3:"IND", NumCode:"356", ISO:"ISO 3166-2:IN", Independent: "Yes" },
    { Name:"Indonesia", Code2:"ID", Code3:"IDN", NumCode:"360", ISO:"ISO 3166-2:ID", Independent: "Yes" },
    { Name:"Iran (Islamic Republic of)", Code2:"IR", Code3:"IRN", NumCode:"364", ISO:"ISO 3166-2:IR", Independent: "Yes" },
    { Name:"Iraq", Code2:"IQ", Code3:"IRQ", NumCode:"368", ISO:"ISO 3166-2:IQ", Independent: "Yes" },
    { Name:"Ireland", Code2:"IE", Code3:"IRL", NumCode:"372", ISO:"ISO 3166-2:IE", Independent: "Yes" },
    { Name:"Isle of Man", Code2:"IM", Code3:"IMN", NumCode:"833", ISO:"ISO 3166-2:IM", Independent: "No" },
    { Name:"Israel", Code2:"IL", Code3:"ISR", NumCode:"376", ISO:"ISO 3166-2:IL", Independent: "Yes" },
    { Name:"Italy", Code2:"IT", Code3:"ITA", NumCode:"380", ISO:"ISO 3166-2:IT", Independent: "Yes" },
    { Name:"Jamaica", Code2:"JM", Code3:"JAM", NumCode:"388", ISO:"ISO 3166-2:JM", Independent: "Yes" },
    { Name:"Japan", Code2:"JP", Code3:"JPN", NumCode:"392", ISO:"ISO 3166-2:JP", Independent: "Yes" },
    { Name:"Jersey", Code2:"JE", Code3:"JEY", NumCode:"832", ISO:"ISO 3166-2:JE", Independent: "No" },
    { Name:"Jordan", Code2:"JO", Code3:"JOR", NumCode:"400", ISO:"ISO 3166-2:JO", Independent: "Yes" },
    { Name:"Kazakhstan", Code2:"KZ", Code3:"KAZ", NumCode:"398", ISO:"ISO 3166-2:KZ", Independent: "Yes" },
    { Name:"Kenya", Code2:"KE", Code3:"KEN", NumCode:"404", ISO:"ISO 3166-2:KE", Independent: "Yes" },
    { Name:"Kiribati", Code2:"KI", Code3:"KIR", NumCode:"296", ISO:"ISO 3166-2:KI", Independent: "Yes" },
    { Name:"Korea (Democratic People's Republic of)", Code2:"KP", Code3:"PRK", NumCode:"408", ISO:"ISO 3166-2:KP", Independent: "Yes" },
    { Name:"Korea, Republic of", Code2:"KR", Code3:"KOR", NumCode:"410", ISO:"ISO 3166-2:KR", Independent: "Yes" },
    { Name:"Kuwait", Code2:"KW", Code3:"KWT", NumCode:"414", ISO:"ISO 3166-2:KW", Independent: "Yes" },
    { Name:"Kyrgyzstan", Code2:"KG", Code3:"KGZ", NumCode:"417", ISO:"ISO 3166-2:KG", Independent: "Yes" },
    { Name:"Lao People's Democratic Republic", Code2:"LA", Code3:"LAO", NumCode:"418", ISO:"ISO 3166-2:LA", Independent: "Yes" },
    { Name:"Latvia", Code2:"LV", Code3:"LVA", NumCode:"428", ISO:"ISO 3166-2:LV", Independent: "Yes" },
    { Name:"Lebanon", Code2:"LB", Code3:"LBN", NumCode:"422", ISO:"ISO 3166-2:LB", Independent: "Yes" },
    { Name:"Lesotho", Code2:"LS", Code3:"LSO", NumCode:"426", ISO:"ISO 3166-2:LS", Independent: "Yes" },
    { Name:"Liberia", Code2:"LR", Code3:"LBR", NumCode:"430", ISO:"ISO 3166-2:LR", Independent: "Yes" },
    { Name:"Libya", Code2:"LY", Code3:"LBY", NumCode:"434", ISO:"ISO 3166-2:LY", Independent: "Yes" },
    { Name:"Liechtenstein", Code2:"LI", Code3:"LIE", NumCode:"438", ISO:"ISO 3166-2:LI", Independent: "Yes" },
    { Name:"Lithuania", Code2:"LT", Code3:"LTU", NumCode:"440", ISO:"ISO 3166-2:LT", Independent: "Yes" },
    { Name:"Luxembourg", Code2:"LU", Code3:"LUX", NumCode:"442", ISO:"ISO 3166-2:LU", Independent: "Yes" },
    { Name:"Macao", Code2:"MO", Code3:"MAC", NumCode:"446", ISO:"ISO 3166-2:MO", Independent: "No" },
    { Name:"Macedonia, the former Yugoslav Republic of", Code2:"MK", Code3:"MKD", NumCode:"807", ISO:"ISO 3166-2:MK", Independent: "Yes" },
    { Name:"Madagascar", Code2:"MG", Code3:"MDG", NumCode:"450", ISO:"ISO 3166-2:MG", Independent: "Yes" },
    { Name:"Malawi", Code2:"MW", Code3:"MWI", NumCode:"454", ISO:"ISO 3166-2:MW", Independent: "Yes" },
    { Name:"Malaysia", Code2:"MY", Code3:"MYS", NumCode:"458", ISO:"ISO 3166-2:MY", Independent: "Yes" },
    { Name:"Maldives", Code2:"MV", Code3:"MDV", NumCode:"462", ISO:"ISO 3166-2:MV", Independent: "Yes" },
    { Name:"Mali", Code2:"ML", Code3:"MLI", NumCode:"466", ISO:"ISO 3166-2:ML", Independent: "Yes" },
    { Name:"Malta", Code2:"MT", Code3:"MLT", NumCode:"470", ISO:"ISO 3166-2:MT", Independent: "Yes" },
    { Name:"Marshall Islands", Code2:"MH", Code3:"MHL", NumCode:"584", ISO:"ISO 3166-2:MH", Independent: "Yes" },
    { Name:"Martinique", Code2:"MQ", Code3:"MTQ", NumCode:"474", ISO:"ISO 3166-2:MQ", Independent: "No" },
    { Name:"Mauritania", Code2:"MR", Code3:"MRT", NumCode:"478", ISO:"ISO 3166-2:MR", Independent: "Yes" },
    { Name:"Mauritius", Code2:"MU", Code3:"MUS", NumCode:"480", ISO:"ISO 3166-2:MU", Independent: "Yes" },
    { Name:"Mayotte", Code2:"YT", Code3:"MYT", NumCode:"175", ISO:"ISO 3166-2:YT", Independent: "No" },
    { Name:"Mexico", Code2:"MX", Code3:"MEX", NumCode:"484", ISO:"ISO 3166-2:MX", Independent: "Yes" },
    { Name:"Micronesia (Federated States of)", Code2:"FM", Code3:"FSM", NumCode:"583", ISO:"ISO 3166-2:FM", Independent: "Yes" },
    { Name:"Moldova, Republic of", Code2:"MD", Code3:"MDA", NumCode:"498", ISO:"ISO 3166-2:MD", Independent: "Yes" },
    { Name:"Monaco", Code2:"MC", Code3:"MCO", NumCode:"492", ISO:"ISO 3166-2:MC", Independent: "Yes" },
    { Name:"Mongolia", Code2:"MN", Code3:"MNG", NumCode:"496", ISO:"ISO 3166-2:MN", Independent: "Yes" },
    { Name:"Montenegro", Code2:"ME", Code3:"MNE", NumCode:"499", ISO:"ISO 3166-2:ME", Independent: "Yes" },
    { Name:"Montserrat", Code2:"MS", Code3:"MSR", NumCode:"500", ISO:"ISO 3166-2:MS", Independent: "No" },
    { Name:"Morocco", Code2:"MA", Code3:"MAR", NumCode:"504", ISO:"ISO 3166-2:MA", Independent: "Yes" },
    { Name:"Mozambique", Code2:"MZ", Code3:"MOZ", NumCode:"508", ISO:"ISO 3166-2:MZ", Independent: "Yes" },
    { Name:"Myanmar", Code2:"MM", Code3:"MMR", NumCode:"104", ISO:"ISO 3166-2:MM", Independent: "Yes" },
    { Name:"Namibia", Code2:"NA", Code3:"NAM", NumCode:"516", ISO:"ISO 3166-2:NA", Independent: "Yes" },
    { Name:"Nauru", Code2:"NR", Code3:"NRU", NumCode:"520", ISO:"ISO 3166-2:NR", Independent: "Yes" },
    { Name:"Nepal", Code2:"NP", Code3:"NPL", NumCode:"524", ISO:"ISO 3166-2:NP", Independent: "Yes" },
    { Name:"Netherlands", Code2:"NL", Code3:"NLD", NumCode:"528", ISO:"ISO 3166-2:NL", Independent: "Yes" },
    { Name:"New Caledonia", Code2:"NC", Code3:"NCL", NumCode:"540", ISO:"ISO 3166-2:NC", Independent: "No" },
    { Name:"New Zealand", Code2:"NZ", Code3:"NZL", NumCode:"554", ISO:"ISO 3166-2:NZ", Independent: "Yes" },
    { Name:"Nicaragua", Code2:"NI", Code3:"NIC", NumCode:"558", ISO:"ISO 3166-2:NI", Independent: "Yes" },
    { Name:"Niger", Code2:"NE", Code3:"NER", NumCode:"562", ISO:"ISO 3166-2:NE", Independent: "Yes" },
    { Name:"Nigeria", Code2:"NG", Code3:"NGA", NumCode:"566", ISO:"ISO 3166-2:NG", Independent: "Yes" },
    { Name:"Niue", Code2:"NU", Code3:"NIU", NumCode:"570", ISO:"ISO 3166-2:NU", Independent: "No" },
    { Name:"Norfolk Island", Code2:"NF", Code3:"NFK", NumCode:"574", ISO:"ISO 3166-2:NF", Independent: "No" },
    { Name:"Northern Mariana Islands", Code2:"MP", Code3:"MNP", NumCode:"580", ISO:"ISO 3166-2:MP", Independent: "No" },
    { Name:"Norway", Code2:"NO", Code3:"NOR", NumCode:"578", ISO:"ISO 3166-2:NO", Independent: "Yes" },
    { Name:"Oman", Code2:"OM", Code3:"OMN", NumCode:"512", ISO:"ISO 3166-2:OM", Independent: "Yes" },
    { Name:"Pakistan", Code2:"PK", Code3:"PAK", NumCode:"586", ISO:"ISO 3166-2:PK", Independent: "Yes" },
    { Name:"Palau", Code2:"PW", Code3:"PLW", NumCode:"585", ISO:"ISO 3166-2:PW", Independent: "Yes" },
    { Name:"Palestine, State of", Code2:"PS", Code3:"PSE", NumCode:"275", ISO:"ISO 3166-2:PS", Independent: "No" },
    { Name:"Panama", Code2:"PA", Code3:"PAN", NumCode:"591", ISO:"ISO 3166-2:PA", Independent: "Yes" },
    { Name:"Papua New Guinea", Code2:"PG", Code3:"PNG", NumCode:"598", ISO:"ISO 3166-2:PG", Independent: "Yes" },
    { Name:"Paraguay", Code2:"PY", Code3:"PRY", NumCode:"600", ISO:"ISO 3166-2:PY", Independent: "Yes" },
    { Name:"Peru", Code2:"PE", Code3:"PER", NumCode:"604", ISO:"ISO 3166-2:PE", Independent: "Yes" },
    { Name:"Philippines", Code2:"PH", Code3:"PHL", NumCode:"608", ISO:"ISO 3166-2:PH", Independent: "Yes" },
    { Name:"Pitcairn", Code2:"PN", Code3:"PCN", NumCode:"612", ISO:"ISO 3166-2:PN", Independent: "No" },
    { Name:"Poland", Code2:"PL", Code3:"POL", NumCode:"616", ISO:"ISO 3166-2:PL", Independent: "Yes" },
    { Name:"Portugal", Code2:"PT", Code3:"PRT", NumCode:"620", ISO:"ISO 3166-2:PT", Independent: "Yes" },
    { Name:"Puerto Rico", Code2:"PR", Code3:"PRI", NumCode:"630", ISO:"ISO 3166-2:PR", Independent: "No" },
    { Name:"Qatar", Code2:"QA", Code3:"QAT", NumCode:"634", ISO:"ISO 3166-2:QA", Independent: "Yes" },
    { Name:"Réunion", Code2:"RE", Code3:"REU", NumCode:"638", ISO:"ISO 3166-2:RE", Independent: "No" },
    { Name:"Romania", Code2:"RO", Code3:"ROU", NumCode:"642", ISO:"ISO 3166-2:RO", Independent: "Yes" },
    { Name:"Russian Federation", Code2:"RU", Code3:"RUS", NumCode:"643", ISO:"ISO 3166-2:RU", Independent: "Yes" },
    { Name:"Rwanda", Code2:"RW", Code3:"RWA", NumCode:"646", ISO:"ISO 3166-2:RW", Independent: "Yes" },
    { Name:"Saint Barthélemy", Code2:"BL", Code3:"BLM", NumCode:"652", ISO:"ISO 3166-2:BL", Independent: "No" },
    { Name:"Saint Helena, Ascension and Tristan da Cunha", Code2:"SH", Code3:"SHN", NumCode:"654", ISO:"ISO 3166-2:SH", Independent: "No" },
    { Name:"Saint Kitts and Nevis", Code2:"KN", Code3:"KNA", NumCode:"659", ISO:"ISO 3166-2:KN", Independent: "Yes" },
    { Name:"Saint Lucia", Code2:"LC", Code3:"LCA", NumCode:"662", ISO:"ISO 3166-2:LC", Independent: "Yes" },
    { Name:"Saint Martin (French part)", Code2:"MF", Code3:"MAF", NumCode:"663", ISO:"ISO 3166-2:MF", Independent: "No" },
    { Name:"Saint Pierre and Miquelon", Code2:"PM", Code3:"SPM", NumCode:"666", ISO:"ISO 3166-2:PM", Independent: "No" },
    { Name:"Saint Vincent and the Grenadines", Code2:"VC", Code3:"VCT", NumCode:"670", ISO:"ISO 3166-2:VC", Independent: "Yes" },
    { Name:"Samoa", Code2:"WS", Code3:"WSM", NumCode:"882", ISO:"ISO 3166-2:WS", Independent: "Yes" },
    { Name:"San Marino", Code2:"SM", Code3:"SMR", NumCode:"674", ISO:"ISO 3166-2:SM", Independent: "Yes" },
    { Name:"Sao Tome and Principe", Code2:"ST", Code3:"STP", NumCode:"678", ISO:"ISO 3166-2:ST", Independent: "Yes" },
    { Name:"Saudi Arabia", Code2:"SA", Code3:"SAU", NumCode:"682", ISO:"ISO 3166-2:SA", Independent: "Yes" },
    { Name:"Senegal", Code2:"SN", Code3:"SEN", NumCode:"686", ISO:"ISO 3166-2:SN", Independent: "Yes" },
    { Name:"Serbia", Code2:"RS", Code3:"SRB", NumCode:"688", ISO:"ISO 3166-2:RS", Independent: "Yes" },
    { Name:"Seychelles", Code2:"SC", Code3:"SYC", NumCode:"690", ISO:"ISO 3166-2:SC", Independent: "Yes" },
    { Name:"Sierra Leone", Code2:"SL", Code3:"SLE", NumCode:"694", ISO:"ISO 3166-2:SL", Independent: "Yes" },
    { Name:"Singapore", Code2:"SG", Code3:"SGP", NumCode:"702", ISO:"ISO 3166-2:SG", Independent: "Yes" },
    { Name:"Sint Maarten (Dutch part)", Code2:"SX", Code3:"SXM", NumCode:"534", ISO:"ISO 3166-2:SX", Independent: "No" },
    { Name:"Slovakia", Code2:"SK", Code3:"SVK", NumCode:"703", ISO:"ISO 3166-2:SK", Independent: "Yes" },
    { Name:"Slovenia", Code2:"SI", Code3:"SVN", NumCode:"705", ISO:"ISO 3166-2:SI", Independent: "Yes" },
    { Name:"Solomon Islands", Code2:"SB", Code3:"SLB", NumCode:"090", ISO:"ISO 3166-2:SB", Independent: "Yes" },
    { Name:"Somalia", Code2:"SO", Code3:"SOM", NumCode:"706", ISO:"ISO 3166-2:SO", Independent: "Yes" },
    { Name:"South Africa", Code2:"ZA", Code3:"ZAF", NumCode:"710", ISO:"ISO 3166-2:ZA", Independent: "Yes" },
    { Name:"South Georgia and the South Sandwich Islands", Code2:"GS", Code3:"SGS", NumCode:"239", ISO:"ISO 3166-2:GS", Independent: "No" },
    { Name:"South Sudan", Code2:"SS", Code3:"SSD", NumCode:"728", ISO:"ISO 3166-2:SS", Independent: "Yes" },
    { Name:"Spain", Code2:"ES", Code3:"ESP", NumCode:"724", ISO:"ISO 3166-2:ES", Independent: "Yes" },
    { Name:"Sri Lanka", Code2:"LK", Code3:"LKA", NumCode:"144", ISO:"ISO 3166-2:LK", Independent: "Yes" },
    { Name:"Sudan", Code2:"SD", Code3:"SDN", NumCode:"729", ISO:"ISO 3166-2:SD", Independent: "Yes" },
    { Name:"Suriname", Code2:"SR", Code3:"SUR", NumCode:"740", ISO:"ISO 3166-2:SR", Independent: "Yes" },
    { Name:"Svalbard and Jan Mayen", Code2:"SJ", Code3:"SJM", NumCode:"744", ISO:"ISO 3166-2:SJ", Independent: "No" },
    { Name:"Sweden", Code2:"SE", Code3:"SWE", NumCode:"752", ISO:"ISO 3166-2:SE", Independent: "Yes" },
    { Name:"Switzerland", Code2:"CH", Code3:"CHE", NumCode:"756", ISO:"ISO 3166-2:CH", Independent: "Yes" },
    { Name:"Syrian Arab Republic", Code2:"SY", Code3:"SYR", NumCode:"760", ISO:"ISO 3166-2:SY", Independent: "Yes" },
    { Name:"Taiwan, Province of China", Code2:"TW", Code3:"TWN", NumCode:"158", ISO:"ISO 3166-2:TW", Independent: "No" },
    { Name:"Tajikistan", Code2:"TJ", Code3:"TJK", NumCode:"762", ISO:"ISO 3166-2:TJ", Independent: "Yes" },
    { Name:"Tanzania, United Republic of", Code2:"TZ", Code3:"TZA", NumCode:"834", ISO:"ISO 3166-2:TZ", Independent: "Yes" },
    { Name:"Thailand", Code2:"TH", Code3:"THA", NumCode:"764", ISO:"ISO 3166-2:TH", Independent: "Yes" },
    { Name:"Timor-Leste", Code2:"TL", Code3:"TLS", NumCode:"626", ISO:"ISO 3166-2:TL", Independent: "Yes" },
    { Name:"Togo", Code2:"TG", Code3:"TGO", NumCode:"768", ISO:"ISO 3166-2:TG", Independent: "Yes" },
    { Name:"Tokelau", Code2:"TK", Code3:"TKL", NumCode:"772", ISO:"ISO 3166-2:TK", Independent: "No" },
    { Name:"Tonga", Code2:"TO", Code3:"TON", NumCode:"776", ISO:"ISO 3166-2:TO", Independent: "Yes" },
    { Name:"Trinidad and Tobago", Code2:"TT", Code3:"TTO", NumCode:"780", ISO:"ISO 3166-2:TT", Independent: "Yes" },
    { Name:"Tunisia", Code2:"TN", Code3:"TUN", NumCode:"788", ISO:"ISO 3166-2:TN", Independent: "Yes" },
    { Name:"Turkey", Code2:"TR", Code3:"TUR", NumCode:"792", ISO:"ISO 3166-2:TR", Independent: "Yes" },
    { Name:"Turkmenistan", Code2:"TM", Code3:"TKM", NumCode:"795", ISO:"ISO 3166-2:TM", Independent: "Yes" },
    { Name:"Turks and Caicos Islands", Code2:"TC", Code3:"TCA", NumCode:"796", ISO:"ISO 3166-2:TC", Independent: "No" },
    { Name:"Tuvalu", Code2:"TV", Code3:"TUV", NumCode:"798", ISO:"ISO 3166-2:TV", Independent: "Yes" },
    { Name:"Uganda", Code2:"UG", Code3:"UGA", NumCode:"800", ISO:"ISO 3166-2:UG", Independent: "Yes" },
    { Name:"Ukraine", Code2:"UA", Code3:"UKR", NumCode:"804", ISO:"ISO 3166-2:UA", Independent: "Yes" },
    { Name:"United Arab Emirates", Code2:"AE", Code3:"ARE", NumCode:"784", ISO:"ISO 3166-2:AE", Independent: "Yes" },
    { Name:"United Kingdom of Great Britain and Northern Ireland", Code2:"GB", Code3:"GBR", NumCode:"826", ISO:"ISO 3166-2:GB", Independent: "Yes" },
    { Name:"United States of America", Code2:"US", Code3:"USA", NumCode:"840", ISO:"ISO 3166-2:US", Independent: "Yes" },
    { Name:"United States Minor Outlying Islands", Code2:"UM", Code3:"UMI", NumCode:"581", ISO:"ISO 3166-2:UM", Independent: "No" },
    { Name:"Uruguay", Code2:"UY", Code3:"URY", NumCode:"858", ISO:"ISO 3166-2:UY", Independent: "Yes" },
    { Name:"Uzbekistan", Code2:"UZ", Code3:"UZB", NumCode:"860", ISO:"ISO 3166-2:UZ", Independent: "Yes" },
    { Name:"Vanuatu", Code2:"VU", Code3:"VUT", NumCode:"548", ISO:"ISO 3166-2:VU", Independent: "Yes" },
    { Name:"Venezuela (Bolivarian Republic of)", Code2:"VE", Code3:"VEN", NumCode:"862", ISO:"ISO 3166-2:VE", Independent: "Yes" },
    { Name:"Viet Nam", Code2:"VN", Code3:"VNM", NumCode:"704", ISO:"ISO 3166-2:VN", Independent: "Yes" },
    { Name:"Virgin Islands (British)", Code2:"VG", Code3:"VGB", NumCode:"092", ISO:"ISO 3166-2:VG", Independent: "No" },
    { Name:"Virgin Islands (U.S.)", Code2:"VI", Code3:"VIR", NumCode:"850", ISO:"ISO 3166-2:VI", Independent: "No" },
    { Name:"Wallis and Futuna", Code2:"WF", Code3:"WLF", NumCode:"876", ISO:"ISO 3166-2:WF", Independent: "No" },
    { Name:"Western Sahara", Code2:"EH", Code3:"ESH", NumCode:"732", ISO:"ISO 3166-2:EH", Independent: "No" },
    { Name:"Yemen", Code2:"YE", Code3:"YEM", NumCode:"887", ISO:"ISO 3166-2:YE", Independent: "Yes" },
    { Name:"Zambia", Code2:"ZM", Code3:"ZMB", NumCode:"894", ISO:"ISO 3166-2:ZM", Independent: "Yes" },
    { Name:"Zimbabwe", Code2:"ZW", Code3:"ZWE", NumCode:"716", ISO:"ISO 3166-2:ZW", Independent: "Yes" }
];